version: "3.9"

services:
  # ------------------------------
  # 1️⃣ WebGoat – web https://github.com/WebGoat/WebGoat
  # ------------------------------
  webgoat:
    image: webgoat/webgoat
    container_name: vulnerable-webapp
    ports:
      - "8080:8080"
    restart: unless-stopped

  # ------------------------------
  # 2️⃣ Vulnerable linux server
  # ------------------------------
  vulnserverlinux:
    build: ./custom-vulnerable
    container_name: vulnerable-linux
    ports:
      - "2222:22"   # SSH
      - "2121:21"   # FTP
      - "8081:80"   # HTTP (Apache)
      - "3307:3306" # MySQL
    restart: unless-stopped
    
 # vulnserverwindows:
